spring.application.name=equipos


server.port = 8001


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@esports_high?TNS_ADMIN=C:/wallet
spring.datasource.username=MS_EQUIPOS
spring.datasource.password=DuocUc..2026

spring.jpa.hibernate.ddl-auto=update


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG